### ISSUE TITLE
[!] Initialization failed with Memory map? Try without MMap

### ISSUE THREAD

**Issue by RyanAMTB** [TTLH20220429/PUBG_DMA#1]
This error appears when launching. Built just fine. 

[!] Initialization failed with Memory map? Try without MMap

Any way to resolve?

**Comment by TTLH20220429** [comment]
Have you added FTD3XX.dllleechcore.dll vmm.dll?

**Comment by RyanAMTB** [comment]
Yes I have all three included. I am going to try an alternate method that has to do with physically adding the memory map later this morning.

the FPGA alterations did not work. Is it possible to simply paste the memory cpp from another cheat I use?

**Comment by TTLH20220429** [comment]
update offset
