### ISSUE TITLE
Every time I debug to this point, it crashes

### ISSUE THREAD

**Issue by suyu926** [TTLH20220429/PUBG_DMA#3]
![微信图片_20241119230814](https://github.com/user-attachments/assets/0afefbea-df18-4919-8137-c913b25e14ae)
How to solve it?

**Comment by TTLH20220429** [comment]
你的解密偏移是否更新了？它指向了错误地址

**Comment by suyu926** [comment]
Can you provide a copy of the latest offset? I use it to compare my offset. I don't know what some names are.

发自我的iPhone


------------------ Original ------------------
From: TTLH20220429 ***@***.***&gt;
Date: Fri,Nov 22,2024 9:33 AM
To: TTLH20220429/PUBG_DMA ***@***.***&gt;
Cc: suyu926 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TTLH20220429/PUBG_DMA] Every time I debug to this point, itcrashes (Issue #3)





 
你的解密偏移是否更新了？它指向了错误地址

**Comment by suyu926** [comment]
![微信图片_20241122111131](https://github.com/user-attachments/assets/558037aa-2f24-42c5-8009-d3c24dd1551c)

I don't know what this is

**Comment by suyu926** [comment]
![微信图片_20241122112334](https://github.com/user-attachments/assets/b23637fc-0b45-46c2-8e62-146dc6bd6051)
The offset is updated, but the ESP is completely wrong

**Comment by TTLH20220429** [comment]
完全复制并替换这段 到 global.h
https://www.unknowncheats.me/forum/4261882-post17571.html

ElementsPerChunk == NameChunk | ChunkId | ElementsPerChunk | IDD

**Comment by marsdadd** [comment]
Will it be solved in the end?

**Comment by suyu926** [comment]
不知道，换源码了



发自我的iPhone


------------------ Original ------------------
From: marsdadd ***@***.***&gt;
Date: Thu,Apr 24,2025 4:57 PM
To: TTLH20220429/PUBG_DMA ***@***.***&gt;
Cc: suyu926 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TTLH20220429/PUBG_DMA] Every time I debug to this point, itcrashes (Issue #3)



 marsdadd left a comment (TTLH20220429/PUBG_DMA#3)
 
Will it be solved in the end?

**Comment by marsdadd** [comment]
> 不知道，换源码了，开发了自己的iPhone
> […](#)

现在开发的怎么样了，换了那个源码，看看你的结果，
我看过这个源码https://github.com/Strimsnaiper/EVO_PUBG-DMA-ESP-main 你看过？
